Rebase/add model class
RVP2-241209-team2/p2-backend pull request #6
Opened 2024-12-27 23:23 UTC by Tachnyan

rebase of @dzieger's feature/add-model-classes branch onto @gyakhoe's work in main branch.

2024-12-29 13:21 UTC, dzieger requested changes
The AddressType enum still has a package of com.rvp2 instead of com.revature. Other than that, I didn't see anything else that looks off.

2024-12-30 13:12 UTC, gyakhoe approved these changes
Looks good.

2024-12-30 13:17 UTC, gyakhoe approved these changes
No issue found.

2024-12-30 18:17 UTC, dzieger approved these changes

2024-12-30 18:18 UTC, merged